name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: alerts_user
          POSTGRES_PASSWORD: alerts_pass
          POSTGRES_DB: alertsdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U alerts"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore IndustrialAlerts.sln

      - name: Build
        run: dotnet build IndustrialAlerts.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test IndustrialAlerts.sln --no-build --configuration Release --verbosity normal
